[package]
name = "wasm-elementary-cellular-automaton"
version = "0.1.0"
edition = "2021"

[dependencies]
elementary-cellular-automaton = "0.1.0"
wasm-bindgen = "0.2.95"

[lib]
crate-type = ["cdylib", "rlib"]
